"""add razorpay_event_id to transactions

Revision ID: 4ae917627462
Revises: 517bfeae9544
Create Date: 2026-08-24 19:58:08.873046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ae917627462'
down_revision: Union[str, Sequence[str], None] = '517bfeae9544'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('razorpay_event_id', sa.String(length=100), nullable=True))
    op.create_unique_constraint(None, 'transactions', ['razorpay_event_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='unique')
    op.drop_column('transactions', 'razorpay_event_id')
    # ### end Alembic commands ###
