"""add audit_events sequence column

Revision ID: 517bfeae9544
Revises: d8bab1ba6281
Create Date: 2026-08-24 18:56:28.625442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '517bfeae9544'
down_revision: Union[str, Sequence[str], None] = 'd8bab1ba6281'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_events', sa.Column('sequence', sa.BigInteger(), sa.Identity(always=True), nullable=False))
    op.create_unique_constraint(None, 'audit_events', ['sequence'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'audit_events', type_='unique')
    op.drop_column('audit_events', 'sequence')
    # ### end Alembic commands ###
