"""add authorization_requests table

Revision ID: 89b10077c4b4
Revises: 6d3a31103127
Create Date: 2026-08-26 20:15:44.336431

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '89b10077c4b4'
down_revision: Union[str, Sequence[str], None] = '6d3a31103127'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authorization_requests',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('cart_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='authorization_request_status'), nullable=False),
    sa.Column('max_amount_minor', sa.Integer(), nullable=False),
    sa.Column('allowed_categories', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('allow_addons', sa.Boolean(), nullable=False),
    sa.Column('delivery_requirement', sa.String(length=50), nullable=False),
    sa.Column('single_use', sa.Boolean(), nullable=False),
    sa.Column('expires_in_hours', sa.Integer(), nullable=False),
    sa.Column('product_type', sa.String(length=200), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('resulting_mandate_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['cart_id'], ['carts.id'], ),
    sa.ForeignKeyConstraint(['resulting_mandate_id'], ['mandates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('authorization_requests')
    # ### end Alembic commands ###
