"""add mandate_id to carts

Revision ID: a53d11a41c37
Revises: 4ae917627462
Create Date: 2026-08-25 20:22:02.710566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a53d11a41c37'
down_revision: Union[str, Sequence[str], None] = '4ae917627462'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('carts', sa.Column('mandate_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'carts', 'mandates', ['mandate_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'carts', type_='foreignkey')
    op.drop_column('carts', 'mandate_id')
    # ### end Alembic commands ###
