"""add user_id to audit_events

Revision ID: d0bc94f8aa37
Revises: 89b10077c4b4
Create Date: 2026-08-26 20:16:28.961779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0bc94f8aa37'
down_revision: Union[str, Sequence[str], None] = '89b10077c4b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_events', sa.Column('user_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'audit_events', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'audit_events', type_='foreignkey')
    op.drop_column('audit_events', 'user_id')
    # ### end Alembic commands ###
